services:
  - type: web
    name: flask-ml-app
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py  # change this to your entry point
    envVars:
      - key: FLASK_ENV
        value: production
      - key: MYSQL_HOST
        value: your-db-host
      - key: MYSQL_USER
        value: your-db-username
      - key: MYSQL_PASSWORD
        value: your-db-password
      - key: MYSQL_DB
        value: your-db-name
